### ISSUE TITLE
need to map the data of mongo to host space when deploying in Docker

### ISSUE THREAD

**Issue by dickens88** [center-for-threat-informed-defense/attack-workbench-frontend#246]
Hi @isaisabel ,

please consider mapping the MongoDB database directory to the host machine when deploying in Docker. the current [docker-compose file](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docker-compose.yml) keep the data the Docker container. Once the container is rebuilt, data is lost.

```
  mongodb:
    container_name: attack-workbench-database
    image: mongo
    ports:
      - "27017:27017"
```
maybe you can mapping the data volume to host so that when the docker rebuild the data is still there
